defaults:   &defaults
  stores:
    - name: memory
      window_length: 72000
    - name: url_logfile
      filename: log/memtracker_urls.log
      logger_class: Logger
    - name: gcstat_logfile
      filename: log/memtracker_gcstat.log
      logger_class: Logger


production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
